config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :mailing_lists

  resources :challenge_statements, except: :show do
    post 'join', on: :member
    post 'close', on: :member
    resources :submissions, except: :destroy
  end
  match 'submit', to: 'challenge_statements#submit', as: 'all_submissions', :via => :get

  #static-pages
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/rules'
  get 'static_pages/challenge_statement_1'
  get 'static_pages/challenge_statement_2'
  get 'static_pages/challenge_statement_3'

  #contact-us
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  #users
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/user' => "challenge_statements#submit", :as => :user_root
  match '/users',   to: 'users#index',   via: 'get'
  post '/download-attachments', to: "users#process_and_create_zip_file", as: 'download_documents'
  #get 'users/:id/uploads' => 'users#uploads', :as => :user_uploads

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end

  def rules
  end

  def challenge_statement_1
    @challenge_statement = ChallengeStatement.find(1)
  end

  def challenge_statement_2
    @challenge_statement = ChallengeStatement.find(2)
  end

  def challenge_statement_3
    @challenge_statement = ChallengeStatement.find(3)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/challenge_statement_1.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Download the font for the page -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

  <!-- Responsive webpage -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Download Bootstrap and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
  .title {
    padding-top: 3%;
    padding-bottom: 3%;
    text-align: center;
    font-family: "Hey November";
    font-size: 20vmin;
  }

  .cs1-container {
    margin: auto;
    max-width: 750px;
    padding-bottom: 3%;
  }

  .cs1-heading {
    font-family: "Raleway Black";
    text-align: center;
  }

  p {
    font-family: "Raleway Semibold";
    text-align: justify;
  }

  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
    text-transform: uppercase;
  }

  .button:hover {
    text-decoration: none;
    color: white;
  }

  .page-foot {
    background-color: #F26648;
    padding-top: 4px;
    padding-bottom: 4px;
    text-align: center;
  }

  .last-link {
    font-family: Raleway;
    font-weight: 900;
    letter-spacing: 4px;
    color: white;
    font-size: 5vmin;
  }

  .notice {
    font-weight: 900;
    color: red;
    text-transform: uppercase;
    text-align: center;
  }
</style>

<body>
<div class="container">
<h1 class="title">2020 NUSSU Welfare Diary</h1>
<div class="cs1-container">
  <p>Design for the AY2020/21 Welfare Diary. The theme of the journal is jewel toned colours with writings in block letters style. The design of the journal should appeal to the NUS student community. </p>
  <h2 class="cs1-heading">Context</h2>
  <p>
    The NUSSU Welfare Diary is published annually by the NUSSU Welfare Committee and is distributed during the NUS Student Life Fair to the NUS population in the month of August. 

    The journal design should include:  
      <ol>
        <li>
        Cover (Design to be embossed on it) 
        <br/>
        a) Name: NUSSU Welfare Diary 
        <br/>
        b) Year: (AY) 2020/2021 
        <br/>
        c) Dark colour(s) (e.g. navy blue, dark brown, black) with accent colour of choice 
        <br/>
        d) Size: A5 with 80 X 110 mm design
        <br/>
        </li>
        <br/>
        <li>Front page (this belongs to…)</li>
        a) Size: A5
        <br/>
        <br/>
        <li>
        Monthly dividers: 1 page per month (Aug 2020 - Jul 2021), with jewel toned colour background of choice, and writings in block letters with font of choice. You may want to add in icons or symbols representative of the respective months to increase the visual appeal (e.g. Christmas tree for December). 
        </li>
        a) Size: A5
        <br/>
      </ol>
    <br/>
  </p>
  <h2 class="cs1-heading">Prizes</h2>
  <div class="cs1-padding">
    <p>First prize:</p>
    <ul>
      <li>Nintendo Switch and</li>
      <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
    </ul>
    <p>Second prize:</p>
    <ul>
      <li>Capitaland Voucher and</li>
      <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
    </ul>
    <p>Third prize:</p>
    <ul>
      <li>Capitaland Voucher and</li>
      <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
    </ul>
    <p>Newcomer Award:</p>
    <ul>
      <li>Wacom Intuos S and</li>
      <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
    </ul>
    <p>
      <i>Note that ONE Newcomer Award will be given to ONE eligible participant whose design is the judges’ favorite among ALL CHALLENGE STATEMENTS. Eligibility criteria for Newcomer Award can be found under <%= link_to "Rules and Regulations", static_pages_rules_path %>. 
      </i>
    </p>
  </div>
  <p class="notice">Please download the challenge brief PDF after joining the challenge!</p>
  <br/><br/>

<div style="text-align: center;">
  <% if current_user == nil || !@challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%=  button_to "Join Challenge Statement", join_challenge_statement_path(@challenge_statement), class: "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <%  end %>

  <% if current_user != nil && @challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%= link_to "Download brief", rails_blob_path(@challenge_statement.zip, disposition: 'attachment'), :class => "button" %>
      <br/>
      <br/>
      <%= link_to "Make a submission", all_submissions_path, :class => "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <%= button_to 'Edit', edit_challenge_statement_path(@challenge_statement), :method => :get %>
      <% if @challenge_statement.is_open %>
        <%= button_to 'Close Challenge Statement', close_challenge_statement_path(@challenge_statement), data: { confirm: 'Are you sure?' }%>
      <% else %>
        <%= button_to 'Open Challenge Statement', close_challenge_statement_path(@challenge_statement),  data: { confirm: 'Are you sure?' }%>
      <% end %>
    <% end %>
  <% end %>
  <br/>
  <br/>
  <%= link_to 'Back', challenge_statements_path %>
  </div>
</div>
</div>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>

</body>
</html>

app/views/static_pages/challenge_statement_2.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Download the font for the page -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

  <!-- Responsive webpage -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Download Bootstrap and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
  .title {
    padding-top: 3%;
    padding-bottom: 3%;
    text-align: center;
    font-family: "Hey November";
    font-size: 17vmin;
  }

  .cs2-container {
    margin: auto;
    max-width: 750px;
    padding-bottom: 3%;
  }

  .cs2-heading {
    font-family: "Raleway Black";
    text-align: center;
  }

  p {
    font-family: "Raleway Semibold";
    text-align: justify;
  }

  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
    text-transform: uppercase;
  }

  .button:hover {
    text-decoration: none;
    color: white;
  }

  .page-foot {
    background-color: #F26648;
    padding-top: 4px;
    padding-bottom: 4px;
    text-align: center;
  }

  .last-link {
    font-family: Raleway;
    font-weight: 900;
    letter-spacing: 4px;
    color: white;
    font-size: 5vmin;
  }

  .notice {
    font-weight: 900;
    color: red;
    text-transform: uppercase;
    text-align: center;
  }
</style>

<body>
<div class="container">
<h1 class="title">Key Visual for NUS Commencement Class Giving 2021</h1>
<div class="cs2-container">
  <p>Create a new, refreshed key visual for NUS Commencement Class Giving 2021. The design should inspire pride in being affiliated with NUS and encourage students to mark their graduation with a gift in support of their juniors. </p>
  <h2 class="cs2-heading">Context</h2>
  <p>
    A key visual is not a logo design, but an effective add-on to the logo. It refers to an image motif used in campaigns in order to enhance brand recognition. The context of a campaign should be easily and quickly grasped from the key visual. 
    <br/>
    <br/>
    The key visual should encapsulate a strong concept that is different from recent years and carry distinct elements that can be replicated in different formats. There is no need to use NUS colours or education and giving-related symbols/icons/motifs (e.g. heart, hands, gift box, plant, book, mortarboard, scroll, etc.). 
    <br/>
    <br/>
    Keep in mind that the Commencement Class Giving key visual will be adapted to suit different messaging and dimensions (e.g. web banners, emailers, lamp post banners, floor stickers, etc).  
    <br/>
    <br/>
    Commencement Class Giving is an annual tradition in which the graduating cohort of NUS comes together to celebrate convocation by making a single gift ($20.21 for Class of 2021) in support of their juniors. By leaving a legacy through their giving, the cohort contributes to current and future students in financial need, as well as activities that will enrich campus life. 
    <br/><br/>
  </p>
  <h2 class="cs2-heading">Prizes</h2>
  <p>First prize:</p>
  <ul>
    <li>Apple iPad (32GB) and</li>
    <li>Apple Pencil (1st Generation) and</li>
    <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Second prize:</p>
  <ul>
    <li>Capitaland Voucher and</li>
    <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Third prize:</p>
  <ul>
    <li>Capitaland Voucher and</li>
    <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Newcomer Award:</p>
  <ul>
    <li>Wacom Intuos S and</li>
    <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>
    <i>Note that ONE Newcomer Award will be given to ONE eligible participant whose design is the judges’ favorite among ALL CHALLENGE STATEMENTS. Eligibility criteria for Newcomer Award can be found under <%= link_to "Rules and Regulations", static_pages_rules_path %>. 
    </i>
  </p>
  <p class="notice">Please download the challenge brief PDF after joining the challenge!</p>
  <br/><br/>

<div style="text-align: center;">
  <% if current_user == nil || !@challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%=  button_to "Join Challenge Statement", join_challenge_statement_path(@challenge_statement), class: "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <%  end %>

  <% if current_user != nil && @challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%= link_to "Download brief", rails_blob_path(@challenge_statement.zip, disposition: 'attachment'), :class => "button" %>
      <br/><br/>
      <%= link_to "Make a submission", all_submissions_path, :class => "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <%= button_to 'Edit', edit_challenge_statement_path(@challenge_statement), :method => :get %>
      <% if @challenge_statement.is_open %>
        <%= button_to 'Close Challenge Statement', close_challenge_statement_path(@challenge_statement), data: { confirm: 'Are you sure?' }%>
      <% else %>
        <%= button_to 'Open Challenge Statement', close_challenge_statement_path(@challenge_statement),  data: { confirm: 'Are you sure?' }%>
      <% end %>
    <% end %>
  <% end %>
  <br/>
  <br/>
  <%= link_to 'Back', challenge_statements_path %>
</div>
</div>
</div>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>

</body>
</html>

app/views/static_pages/challenge_statement_3.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Download the font for the page -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

  <!-- Responsive webpage -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Download Bootstrap and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
  .title {
    padding-top: 3%;
    padding-bottom: 3%;
    text-align: center;
    font-family: "Hey November";
    font-size: 20vmin;
  }

  .cs3-container {
    margin: auto;
    max-width: 750px;
    padding-bottom: 3%;
  }

  .cs3-heading {
    font-family: "Raleway Black";
    text-align: center;
  }

  p {
    font-family: "Raleway Semibold";
    text-align: justify;
  }

  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
    text-transform: uppercase;
  }

  .button:hover {
    text-decoration: none;
    color: white;
  }

  .page-foot {
    background-color: #F26648;
    padding-top: 4px;
    padding-bottom: 4px;
    text-align: center;
  }

  .last-link {
    font-family: Raleway;
    font-weight: 900;
    letter-spacing: 4px;
    color: white;
    font-size: 5vmin;
  }

  .notice {
    font-weight: 900;
    color: red;
    text-transform: uppercase;
    text-align: center;
  }
</style>

<body>
<div class="container">
<h1 class="title">Mascot for NUS IT Security Awareness Campaign</h1>
<div class="cs3-container">
  <p>Create and design a Mascot character, for branding, which can be used in IT Security Awareness Campaign. </p>
  <h2 class="cs3-heading">Context</h2>
  <p>
    This mascot character could be used as character on a website, an email, a poster, an intranet article, videos, and e-Learnings and so on to promote adopting good security habits. This mascot would potentially be converted to 3D format for live size representation. 
    <br/>
    <br/>
    It should be possible to resize it depending on the action, so a high quality graphics format is required. It should both work on a computer screen and on a printed poster.   
    <br/>
    <br/>
    The target audience of mascot are students and staff of NUS. 
    <br/>
    <br/>
  </p>
  <h2 class="cs3-heading">Prizes</h2>
  <p>First prize:</p>
  <ul>
    <li>Apple iPad (32GB) and</li>
    <li>Apple Pencil (1st Generation) and</li>
    <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Second prize:</p>
  <ul>
    <li>Capitaland Voucher and</li>
    <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Third prize:</p>
  <ul>
    <li>Capitaland Voucher and</li>
    <li>6-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>Newcomer Award:</p>
  <ul>
    <li>Wacom Intuos S and</li>
    <li>12-months Adobe Creative Cloud for Individual Complete All Apps membership</li>
  </ul>
  <p>
    <i>Note that ONE Newcomer Award will be given to ONE eligible participant whose design is the judges’ favorite among ALL CHALLENGE STATEMENTS. Eligibility criteria for Newcomer Award can be found under <%= link_to "Rules and Regulations", static_pages_rules_path %>. 
    </i>
  </p>
  <p class="notice">Please download the challenge brief PDF after joining the challenge!</p>
  <br/><br/>

<div style="text-align: center;">
  <% if current_user == nil || !@challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%=  button_to "Join Challenge Statement", join_challenge_statement_path(@challenge_statement), class: "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <%  end %>

  <% if current_user != nil && @challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <% if @challenge_statement.is_open %>
      <%= link_to "Download brief", rails_blob_path(@challenge_statement.zip, disposition: 'attachment'), :class => "button" %>
      <br/>
      <br/>
      <%= link_to "Make a submission", all_submissions_path, :class => "button" %>
    <% else %>
      <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <%= button_to 'Edit', edit_challenge_statement_path(@challenge_statement), :method => :get %>
      <% if @challenge_statement.is_open %>
        <%= button_to 'Close Challenge Statement', close_challenge_statement_path(@challenge_statement), data: { confirm: 'Are you sure?' }%>
      <% else %>
        <%= button_to 'Open Challenge Statement', close_challenge_statement_path(@challenge_statement),  data: { confirm: 'Are you sure?' }%>
      <% end %>
    <% end %>
  <% end %>
  <br/>
  <br/>
  <%= link_to 'Back', challenge_statements_path %>
</div>
</div>
</div>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>

</body>
</html>