config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :mailing_lists

  resources :challenge_statements, except: :show do
    post 'join', on: :member
    post 'close', on: :member
    resources :submissions, except: :destroy
  end
  match 'submit', to: 'challenge_statements#submit', as: 'all_submissions', :via => :get

  #static-pages
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/rules'
  get 'static_pages/challenge_statement_1'
  get 'static_pages/challenge_statement_2'
  get 'static_pages/challenge_statement_3'

  #contact-us
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  #users
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/user' => "challenge_statements#submit", :as => :user_root
  match '/users',   to: 'users#index',   via: 'get'
  post '/download-attachments', to: "users#process_and_create_zip_file", as: 'download_documents'
  #get 'users/:id/uploads' => 'users#uploads', :as => :user_uploads

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :user_email, :body
  validates :name, :body, presence: true
  validates :user_email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Please enter a valid email address" }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
    @mailing_list = MailingList.new
  end

  def create
    @message = Message.new(message_params)
    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      redirect_to new_message_url, notice: "Thank you for your message, we will contact you with a reply through your email soon!"
    else
      @mailing_list = MailingList.new
      render "messages/new"
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:name, :user_email, :body)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<style>
  .submit-button {
    text-align: center;
    padding-bottom: 10%;
  }

  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
  }

  .hide-label {
    display: none;
  }

  .centralize {
    text-align: center;
  }

  form {
    display: inline-block;
  }

  input[type=text], textarea, #message_body {
    max-width: 85vw;
    width: 450px;
    border: 2px solid #111f36;
    border-radius: 0px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    font-family: "Raleway";
    font-weight: bold;
    letter-spacing: 2px;
    margin-left: 7%;
  }

  textarea {
    resize: none;
  }

  img {
    position: absolute;
  }

  .custom-form {
    text-align: left;
  }

</style>

<div class="container centralize">

<%= form_with(model: @message, url: create_message_url, local: true) do |form| %>

  <div class="form-group custom-form">
    <div class="field asterisk">
      <%= form.label :name, class: 'hide-label' %>
      <div class="custom-icon" >
      <%= image_tag("logo-username.png", height: "40px") %>
      </div>
    </div>

    <div>
      <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
      <% if @message.errors.any? && @message.errors.include?(:name) %>
        <div class="invalid-feedback d-block">
          <%  @message.errors.messages[:name].each do |error| %>
            <% error.insert(0, "Name ") %>
          <% end %>
          <%=  @message.errors.messages[:name].join(", ") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group custom-form">
    <div class="field asterisk">
      <%= form.label :user_email, class: 'hide-label' %>
      <%= image_tag("logo-email.png", height: "40px") %>
    </div>

    <div>
      <%= form.text_field :user_email, class: 'form-control', placeholder: 'Email' %>
      <% if @message.errors.any? && @message.errors.include?(:user_email) %>
        <div class="invalid-feedback d-block">
          <%=  @message.errors.messages[:user_email].join(", ") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-group custom-form">
    <div class="field asterisk">
      <%= form.label :body, class: 'hide-label' %>
      <%= image_tag("logo-question-mark.png", height: "40px") %>
    </div>

    <div>
      <%= form.text_area :body, class: 'form-control', placeholder: 'Type your inquiry here' %>
      <% if @message.errors.any? && @message.errors.include?(:body) %>
        <div class="invalid-feedback d-block">
          <%  @message.errors.messages[:body].each do |error| %>
            <% error.insert(0, "Message ") %>
          <% end %>
          <%=  @message.errors.messages[:body].join(", ") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions pt-3 submit-button">
    <%= form.submit "SUBMIT", class: 'button' %>
  </div>

<% end %>
</div>

app/views/messages/new.html.erb
<!DOCTYPE html>
<html>

<head>
	<!-- Download the font for the page -->
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

	<!-- Responsive webpage -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Download Bootstrap and dependencies -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
	.title {
		padding-top: 3%;
		text-align: center;
		font-family: "Hey November";
		font-size: 20vmin;
	}

	.subtitle {
		font-family: "Raleway Black";
        text-align: center;
        letter-spacing: 3px;
        font-size: 150%;
        padding-bottom: 3%;
	}

	.separator {
	 	font-family: "Raleway";
	 	text-align: center;
	 	font-style: italic;
	}

	.line {
		width: 100%; 
	    text-align: center; 
	    border-bottom: 1px solid #000; 
	    line-height: 0.1em;
	    margin: 2% 0 2%; 
	}

	.line .separator {
		background:#F6F7F2; 
    	padding:0 30px;
	}

	.page-foot {
        background-color: #F26648;
        padding-top: 4px;
        padding-bottom: 4px;
        text-align: center;
    }

    .last-link {
        font-family: Raleway;
        font-weight: 900;
        letter-spacing: 4px;
        color: white;
        font-size: 5vmin;
    }
</style>

<body>
<h1 class="title">CONTACT US!</h1>
<h2 class="subtitle">ANYTHING YOU WANT TO ASK US?</h2>

<%= render 'messages/form', message: @message %>

<div class="container">
	<p class="line"><span class="separator">OR</span></p>
</div>

<h1 class="title">SUBSCRIBE FOR MORE UPDATE!</h1>
<%= render "mailing_lists/new", mailing_list: @mailing_list %>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>
</body>
</html>