config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :mailing_lists

  resources :challenge_statements, except: :show do
    post 'join', on: :member
    post 'close', on: :member
    resources :submissions, except: :destroy
  end
  match 'submit', to: 'challenge_statements#submit', as: 'all_submissions', :via => :get

  #static-pages
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/rules'
  get 'static_pages/challenge_statement_1'
  get 'static_pages/challenge_statement_2'
  get 'static_pages/challenge_statement_3'

  #contact-us
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  #users
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/user' => "challenge_statements#submit", :as => :user_root
  match '/users',   to: 'users#index',   via: 'get'
  post '/download-attachments', to: "users#process_and_create_zip_file", as: 'download_documents'
  #get 'users/:id/uploads' => 'users#uploads', :as => :user_uploads

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :challenge_statement
  belongs_to :user
  validates :challenge_statement_id, uniqueness: { scope: :user_id, message: "You've already submitted
             a submission for this challenge statement!" }
  validates :file, presence: true
  has_one_attached :file
  def has_submit?
    return if Submission.exists?(user: user, challenge_statement_id: challenge_statement_id)
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:edit, :update]
  load_and_authorize_resource :challenge_statement
  load_and_authorize_resource :submission, through: :challenge_statement

  # GET /submit
  # GET /submit.json

  # GET /submit/new
  def new
    @challenge_statement = ChallengeStatement.find(params[:challenge_statement_id])
    @submission = @challenge_statement.submissions.new
    @submission.user_id = current_user.id
  end

  # GET /submit/1/edit
  def edit
  end

  # POST /submit
  # POST /submit.json
  def create
    @challenge_statement = ChallengeStatement.find(params[:challenge_statement_id])
    @submission = @challenge_statement.submissions.new(submission_params)
    #@submission.assign_attributes( {:challenge_statement_id => @challenge_statement.id} )
    #authorize! :create, @submission
    @submission.user_id = current_user.id
    respond_to do |format|
      if @submission.save
        #SubmissionMailer.submit_upload(@submission).deliver_now
        format.html { redirect_to all_submissions_path, notice: 'Submission was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submit/1
  # PATCH/PUT /submit/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        SubmissionMailer.submit_upload(@submission).deliver_now
        format.html { redirect_to all_submissions_path, notice: 'Submission was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @challenge_statement = ChallengeStatement.find(params[:challenge_statement_id])
      @submission = @challenge_statement.submissions.find(params[:id])
    end


    def has_submit?
      return if Submission.exists?(user: user, challenge_statement_id: challenge_statement_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :file)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<style>
  .field {
    font-weight: bold;
    font-size: 120%;
  }

  .upload-button {
    text-align: center;
    padding-bottom: 3%;
  }

  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
  }
</style>

<%= form_with(model: @submission, url: [@challenge_statement, @submission], local: true) do |form| %>

  <div class="form-group">
  <div class="field">
    <%= form.label :file, "Submit a new file here" %>
  </div>
  <div class="custom-file">
    <%= form.file_field :file, direct_upload: true, class: "custom-file-input" %>
    <label class="custom-file-label" for="submission_file">Choose file...</label>
    <% if @submission.errors.any? && @submission.errors.include?(:file) %>
      <div class="invalid-feedback d-block">
        <%  @submission.errors.messages[:file].each do |error| %>
          <% error.insert(0, "File ") %>
        <% end %>
        <%=  @submission.errors.messages[:file].join(", ") %>
      </div>
    <% end %>
  </div>
  </div>

  <%= form.hidden_field  :title, value: @challenge_statement.partner_name + "_" + current_user.name %>

  <div class="actions form-group upload-button">
    <%= form.submit "UPLOAD", class:"button" %>
  </div>
<% end %>

<script>
  document.querySelector('.custom-file-input').addEventListener('change',function(e){
    var fileName = document.getElementById("submission_file").files[0].name;
    var nextSibling = e.target.nextElementSibling;
    nextSibling.innerText = fileName;
  });
</script>

app/views/submissions/_homepage.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-143760368-2');
</script>
<style>
  .button {
    font-family: "Raleway";
    background-color: #111f36;
    border: none;
    color: white;
    text-align: center;
    letter-spacing: 2px;
    padding-top: 7px;
    padding-bottom: 7px;
    padding-left: 21px;
    padding-right: 21px;
  }
</style>

<table>
  <thead>
  <tr>
    <% if current_user.admin %>
      <th>User</th>
    <% end %>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @submissions.each do |submission| %>
    <tr>
      <td> <%= link_to submission.file.filename, rails_blob_path(submission.file, disposition: 'attachment') %> </td> 
    </tr>
    <tr>
      <% if current_user.admin %>
         <td><%= submission.user.email %></td>
      <% end %>
    </tr>
    <tr>
      <% if !current_user.admin %>
        <% if @challenge_statement.is_open %>
          <td><br/><%= button_to 'REUPLOAD SUBMISSION',  edit_challenge_statement_submission_path(@challenge_statement, submission) , :method => :get, class:"button" %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<% if current_user.admin %>
  <h5>User that has joined but haven't submitted (<%= @not_submitted_user.length %> / <%= @challenge_statement.submissions.count + @not_submitted_user.length %>)</h5>
  <table>
    <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @not_submitted_user.each do |user| %>
      <tr>
        <td><%= user.email %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<br>

<% if user_signed_in? %>
  <% if @challenge_statement.is_open %>
    <% if !current_user.has_submit_for_joined_challenge?(@submissions,current_user) && !current_user.admin && current_user.has_joined_challenge?(@challenge_statement.id) %>
      <%= button_to 'MAKE A NEW SUBMISSION',  new_challenge_statement_submission_path(@challenge_statement), :method => :get, class:"button" %>
    <% elsif !current_user.admin && !current_user.has_joined_challenge?(@challenge_statement.id) %>
      <%= button_to "JOIN CHALLENGE STATEMENT", join_challenge_statement_path(@challenge_statement), class:"button" %>
    <% end %>
  <% else %>
    <%= "Thank you for your interest in Creation 2020, currently we are no longer accepting submissions for this Challenge Statement!" %>
  <% end %>
<% end %>

app/views/submissions/_index.html.erb
<h1>Submissions</h1>

<table>
  <thead>
  <tr>
    <th>File</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @submissions.each do |submission| %>
    <tr>
      <td> <%= link_to submission.file.filename, rails_blob_path(submission.file, disposition: 'attachment') %></td>
      <td><%= submission.user.email %></td>
      <% if !current_user.admin %>
        <td><%= link_to 'Edit',  edit_challenge_statement_submission_path(@challenge_statement, submission) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <% if !@submissions.any?{|submission| submission.user_id == current_user.id } && !current_user.admin && @challenge_statement.id.in?(current_user.joined_challenge_statement) %>
    <%= link_to 'Add a Submission',  new_challenge_statement_submission_path(@challenge_statement) %>
  <% end %>
<% end %>

app/views/submissions/edit.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Download the font for the page -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

  <!-- Responsive webpage -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Download Bootstrap and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
  .title {
    padding-top: 3%;
    padding-bottom: 3%;
    text-align: center;
    font-family: "Hey November";
    font-size: 20vmin;
  }

  .centralize {
  	text-align: center;
  }

  * {
  	font-family: "Raleway";
  }

  .page-foot {
    background-color: #F26648;
    padding-top: 4px;
    padding-bottom: 4px;
    text-align: center;
  }

  .last-link {
    font-family: Raleway;
    font-weight: 900;
    letter-spacing: 4px;
    color: white;
    font-size: 5vmin;
  }
</style>

<body>
<h1 class="title">REUPLOAD SUBMISSION</h1>

<div class="container centralize">
<%= render 'form', submission: @submission %>

<%= link_to 'Back', all_submissions_path %><br/><br/><br/><br/><br/><br/>
</div>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>
</body>
</html>

app/views/submissions/new.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Download the font for the page -->
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />

  <!-- Responsive webpage -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Download Bootstrap and dependencies -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143760368-2"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-143760368-2');
  </script>
</head>

<style>
  .title {
    padding-top: 3%;
    padding-bottom: 3%;
    text-align: center;
    font-family: "Hey November";
    font-size: 20vmin;
  }

  .centralize {
  	text-align: center;
  }

  * {
  	font-family: "Raleway";
  }

  .page-foot {
    background-color: #F26648;
    padding-top: 4px;
    padding-bottom: 4px;
    text-align: center;
  }

  .last-link {
    font-family: Raleway;
    font-weight: 900;
    letter-spacing: 4px;
    color: white;
    font-size: 5vmin;
  }
</style>

<body>
<h1 class="title">NEW SUBMISSION</h1>

<div class="container centralize">
<%= render 'form', submission: @submission %>

<%= link_to 'Back', all_submissions_path %><br/><br/><br/><br/><br/><br/>
</div>

<div class="page-foot"><%= link_to "ANY QUESTIONS?", new_message_path, class: 'last-link' %></div>
</body>
</html>