config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :mailing_lists

  resources :challenge_statements, except: :show do
    post 'join', on: :member
    post 'close', on: :member
    resources :submissions, except: :destroy
  end
  match 'submit', to: 'challenge_statements#submit', as: 'all_submissions', :via => :get

  #static-pages
  get 'static_pages/home'
  get 'static_pages/faq'
  get 'static_pages/rules'
  get 'static_pages/challenge_statement_1'
  get 'static_pages/challenge_statement_2'
  get 'static_pages/challenge_statement_3'

  #contact-us
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  #users
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/user' => "challenge_statements#submit", :as => :user_root
  match '/users',   to: 'users#index',   via: 'get'
  post '/download-attachments', to: "users#process_and_create_zip_file", as: 'download_documents'
  #get 'users/:id/uploads' => 'users#uploads', :as => :user_uploads

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
end

app/views/layouts/_header.html.erb
<style>
  * {
    font-family: "Raleway";
  }
</style>

<header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFCA0B">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if current_page?(static_pages_home_path) %>">
            <%= link_to 'CREATION 2020', static_pages_home_path, id: "logo", class: 'nav-item nav-link' %>
          </li>

          <li class="nav-item <%= 'active' if current_page?(challenge_statements_path) %>">
            <%= link_to 'Challenges', challenge_statements_path , class: 'nav-item nav-link' %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item <%= 'active' if current_page?('/submit') %>">
              <%= link_to 'Submissions',  all_submissions_path  , class: 'nav-item nav-link' %>
            </li>
          <% end %>

          <li class="nav-item <%= 'active' if current_page?(static_pages_rules_path) %>">
            <%= link_to "Rules and Regulations", static_pages_rules_path, class: 'nav-link' %>
          </li>

          <li class="nav-item <%= 'active' if current_page?(static_pages_faq_path) %>">
            <%= link_to "FAQ", static_pages_faq_path, class: 'nav-link' %>
          </li>

          <li class="nav-item <%= 'active' if current_page?('/contact-us') %>">
            <%= link_to "Contact Us", new_message_path, class: 'nav-link' %>
          </li>


          <li class="navbar-right">
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li><%= link_to 'Mailing List', mailing_lists_path , class: 'nav-item nav-link' %></li>
                <li><%= link_to 'All Users', users_index_path , class: 'nav-item nav-link' %></li>
              <% end %>
                <li class="nav-item <%= 'active' if current_page?(edit_user_registration_path) %>">
                  <%= link_to 'Profile', edit_user_registration_path, class: 'nav-item nav-link' %>
                </li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %></li>
            <% else %>
              <li class="nav-item <%= 'active' if current_page?('/users/sign_in') %>">
                <%= link_to 'Log In', new_user_session_path, class: 'nav-item nav-link' %>
              </li>
              <li class="nav-item <%= 'active' if current_page?('/users/sign_up') %>">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-item nav-link' %>
              </li>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="width: 100%; overflow-x: hidden;">
  <head>
    <title>CREATION 2020 - Design Competition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body style="overflow-x: hidden; background-color: #f6f7f2;">
    <% flash.each do |type, text| %>
      <div class="<%= flash_class(type.to_sym) %>  mb-0">
        <a href="#" class="" data-dismiss="alert" aria-label="close">&times;</a>
        <%= text %>
      </div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>